🔧 chore(deploy): comment out publish-indexes step in deploy.yml for troubleshooting

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -103,34 +103,35 @@ jobs:
           command: pages deploy cf-pages --project-name=community-server-docs --branch=main
           #wranglerVersion: 3.101.0
 
-  publish-indexes:
-    needs: [ build, test, deploy ]
-    runs-on: ubuntu-latest
-    container:
-      image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:latest
-
-    steps:
-      - name: Download artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: docs
-          path: artifacts
-
-      - name: Unzip Algolia artifact
-        run: unzip -O UTF-8 -qq "artifacts/${{ needs.build.outputs.algolia_artifact }}" -d algolia-indexes
-
-      - name: Update Algolia Index
-        run: |
-          if [ -z "${{ secrets.ALGOLIA_KEY }}" ]; then
-            echo "ALGOLIA_KEY secret is not set in GitHub Secrets"
-            exit 1
-          else
-            env "algolia-key=${{ secrets.ALGOLIA_KEY }}" java -jar /opt/builder/help-publication-agent.jar \
-            update-index \
-            --application-name ${{ env.ALGOLIA_APP_NAME }} \
-            --index-name ${{ env.ALGOLIA_INDEX_NAME }} \
-            --product ${{ env.CONFIG_JSON_PRODUCT }} \
-            --version ${{ env.CONFIG_JSON_VERSION }} \
-            --index-directory algolia-indexes/ \
-            2>&1 | tee algolia-update-index-log.txt
-          fi
+# see: https://youtrack.jetbrains.com/issue/WRS-7233/Algolia-publisher-2.0.32-3-fails-with-UnrecognizedPropertyException-for-contentBoost-field-generated-by-Writerside-builder
+#  publish-indexes:
+#    needs: [ build, test, deploy ]
+#    runs-on: ubuntu-latest
+#    container:
+#      image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:latest
+#
+#    steps:
+#      - name: Download artifact
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: docs
+#          path: artifacts
+#
+#      - name: Unzip Algolia artifact
+#        run: unzip -O UTF-8 -qq "artifacts/${{ needs.build.outputs.algolia_artifact }}" -d algolia-indexes
+#
+#      - name: Update Algolia Index
+#        run: |
+#          if [ -z "${{ secrets.ALGOLIA_KEY }}" ]; then
+#            echo "ALGOLIA_KEY secret is not set in GitHub Secrets"
+#            exit 1
+#          else
+#            env "algolia-key=${{ secrets.ALGOLIA_KEY }}" java -jar /opt/builder/help-publication-agent.jar \
+#            update-index \
+#            --application-name ${{ env.ALGOLIA_APP_NAME }} \
+#            --index-name ${{ env.ALGOLIA_INDEX_NAME }} \
+#            --product ${{ env.CONFIG_JSON_PRODUCT }} \
+#            --version ${{ env.CONFIG_JSON_VERSION }} \
+#            --index-directory algolia-indexes/ \
+#            2>&1 | tee algolia-update-index-log.txt
+#          fi
